services:
  dev:
    image: ghcr.io/flipstone/haskell-tools:debian-ghc-9.10.3-build-2026.9.11.62@sha256:bef7312b41630fb7dcfd9e39c4db977c0f21078794ded50d9b2935ab1f99e143
    environment:
      STACK_ROOT: /stack-root
      IN_DEV_CONTAINER: 'true'
      # Pass through the CI variable from GitHub (or set it to `true` locally
      # for debugging CI builds)
      CI:
    volumes:
      - .:${PROJECT_DIR}
      - flipstone_stack_root:/stack-root
    working_dir: ${PROJECT_DIR}
    tty: true

volumes:
  flipstone_stack_root:
    external: true
