services:
  dev:
    image: ghcr.io/flipstone/haskell-tools:debian-ghc-9.10.3-build-2026.8.7.56@sha256:ba140d293971c86a850b2d20e1636c72554fc7163b4aea7c26c5d0be87c64b96
    environment:
      STACK_ROOT: /stack-root
      IN_DEV_CONTAINER: 'true'
      # Pass through the CI variable from GitHub (or set it to `true` locally
      # for debugging CI builds)
      CI:
    volumes:
      - .:${PROJECT_DIR}
      - flipstone_stack_root:/stack-root
    working_dir: ${PROJECT_DIR}
    tty: true

volumes:
  flipstone_stack_root:
    external: true
