name:                rollbar
version:             2.2.1.1
synopsis:            error tracking through rollbar.com
homepage:            https://github.com/flipstone/rollbar-haskell
license:             MIT
author:              Flipstone Technology Partners
maintainer:          development@flipstone.com
copyright:           Daggerboard Inc. makers of docmunch.com, Azara Solutions Inc.
category:            Logging

language: Haskell2010

default-extensions:
  - ImportQualifiedPost
  - FlexibleContexts

tested-with:
   GHC == 8.10.7, GHC == 9.0.2, GHC == 9.4.7, GHC == 9.6.7, GHC == 9.8.4, GHC == 9.10.2

flags:
  ci:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

when:
  - condition: flag(ci)
    then:
      ghc-options:
        - -Wall
        - -Werror
        - -Wcompat
        - -Wcpp-undef
        - -Widentities
        - -Wincomplete-uni-patterns
        - -Wincomplete-patterns
        - -Wincomplete-record-updates
        - -Wmissing-export-lists
        - -Wnoncanonical-monad-instances
        - -Wredundant-constraints
        - -Wpartial-fields
        - -Wmissed-specialisations
        - -Wno-implicit-prelude
        - -Wno-safe
        - -Wno-unsafe
      when:
        - condition: impl (ghc >= 9.8)
          ghc-options:
            - -Wterm-variable-capture
            - -Wextended-warnings
    else:
      ghc-options:
        - -Wall

dependencies:
  - base >=4.6 && < 5
  - text >=1.2 && < 2.2
  - aeson >=1.2 && < 2.3
  - vector >=0.12 && < 0.14
  - network >=2.6 && < 3.3
  - monad-control >=1.0.2 && < 1.0.4
  - resourcet >=1.1 && < 1.4
  - http-conduit >=2.2 && < 2.4
  - lifted-base == 0.2.3.*

library:
  source-dirs: src
  exposed-modules:
  - Rollbar
  - Rollbar.MonadLogger
