name: Build and Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

defaults:
  run:
    shell: bash

jobs:
  find-stack-yamls:
    name: Find stack.yamls for GHC Matrix
    runs-on: ubuntu-22.04
    outputs:
      stack-yamls: ${{ steps.set-output.outputs.stack-yamls }}
    steps:
      - name: Find Stack Yamls
        id: set-output
        uses: flipstone/github-actions/find-stack-ghc-yamls@bef3396e6c3777767d1d4837203cfdb2635b4933

  build:
    name: Build and Test
    needs: find-stack-yamls
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5
      matrix:
        stack-yaml: ${{ fromJson(needs.find-stack-yamls.outputs.stack-yamls) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        env:
          cache-version: v3
        with:
          key: ${{ env.cache-version }}-${{ matrix.stack-yaml }}-${{ hashFiles(matrix.stack-yaml, 'stack.yaml', 'package.yaml') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ matrix.stack-yaml }}-
          path: |
            ./stack-root

      - name: Setup Stack
        uses: flipstone/github-actions/setup-dockerized-stack@bef3396e6c3777767d1d4837203cfdb2635b4933
        with:
          stack-root: ./stack-root

      - name: Build and test
        run: ./scripts/test --stack-yaml ${{ matrix.stack-yaml }}

  cabal-check:
    name: Cabal Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Stack (for docker env)
        uses: flipstone/github-actions/setup-dockerized-stack@bef3396e6c3777767d1d4837203cfdb2635b4933
        with:
          stack-root: ./stack-root

      - name: Check for Hackage releasable issues
        run: docker compose run --rm dev cabal check
